// ram1.v

// Generated using ACDS version 19.4 64

`timescale 1 ps / 1 ps
module ram1 (
		input  wire [31:0] data,    //    data.datain
		output wire [31:0] q,       //       q.dataout
		input  wire [11:0] address, // address.address
		input  wire        wren,    //    wren.wren
		input  wire        clock    //   clock.clk
	);

	ram1_ram_1port_2000_dumndey ram_1port_0 (
		.data    (data),    //   input,  width = 32,    data.datain
		.q       (q),       //  output,  width = 32,       q.dataout
		.address (address), //   input,  width = 12, address.address
		.wren    (wren),    //   input,   width = 1,    wren.wren
		.clock   (clock)    //   input,   width = 1,   clock.clk
	);

endmodule
