// SRAM_SC_altera_mm_interconnect_191_mfi3nlq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.4 64

`timescale 1 ps / 1 ps
module SRAM_SC_altera_mm_interconnect_191_mfi3nlq (
		input  wire [31:0] master_1_master_address,                                          //                                            master_1_master.address
		output wire        master_1_master_waitrequest,                                      //                                                           .waitrequest
		input  wire [3:0]  master_1_master_byteenable,                                       //                                                           .byteenable
		input  wire        master_1_master_read,                                             //                                                           .read
		output wire [31:0] master_1_master_readdata,                                         //                                                           .readdata
		output wire        master_1_master_readdatavalid,                                    //                                                           .readdatavalid
		input  wire        master_1_master_write,                                            //                                                           .write
		input  wire [31:0] master_1_master_writedata,                                        //                                                           .writedata
		output wire [9:0]  onchip_memory2_1_s1_address,                                      //                                        onchip_memory2_1_s1.address
		output wire        onchip_memory2_1_s1_write,                                        //                                                           .write
		input  wire [31:0] onchip_memory2_1_s1_readdata,                                     //                                                           .readdata
		output wire [31:0] onchip_memory2_1_s1_writedata,                                    //                                                           .writedata
		output wire [3:0]  onchip_memory2_1_s1_byteenable,                                   //                                                           .byteenable
		output wire        onchip_memory2_1_s1_chipselect,                                   //                                                           .chipselect
		output wire        onchip_memory2_1_s1_clken,                                        //                                                           .clken
		input  wire        master_1_master_translator_reset_reset_bridge_in_reset_reset,     //     master_1_master_translator_reset_reset_bridge_in_reset.reset
		input  wire        onchip_memory2_1_s1_translator_reset_reset_bridge_in_reset_reset, // onchip_memory2_1_s1_translator_reset_reset_bridge_in_reset.reset
		input  wire        clock_in_out_clk_clk                                              //                                           clock_in_out_clk.clk
	);

	wire         master_1_master_translator_avalon_universal_master_0_waitrequest;   // onchip_memory2_1_s1_translator:uav_waitrequest -> master_1_master_translator:uav_waitrequest
	wire  [31:0] master_1_master_translator_avalon_universal_master_0_readdata;      // onchip_memory2_1_s1_translator:uav_readdata -> master_1_master_translator:uav_readdata
	wire         master_1_master_translator_avalon_universal_master_0_debugaccess;   // master_1_master_translator:uav_debugaccess -> onchip_memory2_1_s1_translator:uav_debugaccess
	wire  [31:0] master_1_master_translator_avalon_universal_master_0_address;       // master_1_master_translator:uav_address -> onchip_memory2_1_s1_translator:uav_address
	wire         master_1_master_translator_avalon_universal_master_0_read;          // master_1_master_translator:uav_read -> onchip_memory2_1_s1_translator:uav_read
	wire   [3:0] master_1_master_translator_avalon_universal_master_0_byteenable;    // master_1_master_translator:uav_byteenable -> onchip_memory2_1_s1_translator:uav_byteenable
	wire         master_1_master_translator_avalon_universal_master_0_readdatavalid; // onchip_memory2_1_s1_translator:uav_readdatavalid -> master_1_master_translator:uav_readdatavalid
	wire         master_1_master_translator_avalon_universal_master_0_lock;          // master_1_master_translator:uav_lock -> onchip_memory2_1_s1_translator:uav_lock
	wire         master_1_master_translator_avalon_universal_master_0_write;         // master_1_master_translator:uav_write -> onchip_memory2_1_s1_translator:uav_write
	wire  [31:0] master_1_master_translator_avalon_universal_master_0_writedata;     // master_1_master_translator:uav_writedata -> onchip_memory2_1_s1_translator:uav_writedata
	wire   [2:0] master_1_master_translator_avalon_universal_master_0_burstcount;    // master_1_master_translator:uav_burstcount -> onchip_memory2_1_s1_translator:uav_burstcount

	SRAM_SC_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) master_1_master_translator (
		.clk                    (clock_in_out_clk_clk),                                               //   input,   width = 1,                       clk.clk
		.reset                  (master_1_master_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                     reset.reset
		.uav_address            (master_1_master_translator_avalon_universal_master_0_address),       //  output,  width = 32, avalon_universal_master_0.address
		.uav_burstcount         (master_1_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (master_1_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (master_1_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (master_1_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (master_1_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (master_1_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (master_1_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (master_1_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (master_1_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (master_1_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (master_1_master_address),                                            //   input,  width = 32,      avalon_anti_master_0.address
		.av_waitrequest         (master_1_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_byteenable          (master_1_master_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_read                (master_1_master_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (master_1_master_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (master_1_master_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (master_1_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (master_1_master_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                               // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                               // (terminated),                                        
		.av_begintransfer       (1'b0),                                                               // (terminated),                                        
		.av_chipselect          (1'b0),                                                               // (terminated),                                        
		.av_lock                (1'b0),                                                               // (terminated),                                        
		.av_debugaccess         (1'b0),                                                               // (terminated),                                        
		.uav_clken              (),                                                                   // (terminated),                                        
		.av_clken               (1'b1),                                                               // (terminated),                                        
		.uav_response           (2'b00),                                                              // (terminated),                                        
		.av_response            (),                                                                   // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                               // (terminated),                                        
		.av_writeresponsevalid  ()                                                                    // (terminated),                                        
	);

	SRAM_SC_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) onchip_memory2_1_s1_translator (
		.clk                    (clock_in_out_clk_clk),                                               //   input,   width = 1,                      clk.clk
		.reset                  (onchip_memory2_1_s1_translator_reset_reset_bridge_in_reset_reset),   //   input,   width = 1,                    reset.reset
		.uav_address            (master_1_master_translator_avalon_universal_master_0_address),       //   input,  width = 32, avalon_universal_slave_0.address
		.uav_burstcount         (master_1_master_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (master_1_master_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (master_1_master_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (master_1_master_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (master_1_master_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (master_1_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (master_1_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (master_1_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (master_1_master_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (master_1_master_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (onchip_memory2_1_s1_address),                                        //  output,  width = 10,      avalon_anti_slave_0.address
		.av_write               (onchip_memory2_1_s1_write),                                          //  output,   width = 1,                         .write
		.av_readdata            (onchip_memory2_1_s1_readdata),                                       //   input,  width = 32,                         .readdata
		.av_writedata           (onchip_memory2_1_s1_writedata),                                      //  output,  width = 32,                         .writedata
		.av_byteenable          (onchip_memory2_1_s1_byteenable),                                     //  output,   width = 4,                         .byteenable
		.av_chipselect          (onchip_memory2_1_s1_chipselect),                                     //  output,   width = 1,                         .chipselect
		.av_clken               (onchip_memory2_1_s1_clken),                                          //  output,   width = 1,                         .clken
		.av_read                (),                                                                   // (terminated),                                       
		.av_begintransfer       (),                                                                   // (terminated),                                       
		.av_beginbursttransfer  (),                                                                   // (terminated),                                       
		.av_burstcount          (),                                                                   // (terminated),                                       
		.av_readdatavalid       (1'b0),                                                               // (terminated),                                       
		.av_waitrequest         (1'b0),                                                               // (terminated),                                       
		.av_writebyteenable     (),                                                                   // (terminated),                                       
		.av_lock                (),                                                                   // (terminated),                                       
		.uav_clken              (1'b0),                                                               // (terminated),                                       
		.av_debugaccess         (),                                                                   // (terminated),                                       
		.av_outputenable        (),                                                                   // (terminated),                                       
		.uav_response           (),                                                                   // (terminated),                                       
		.av_response            (2'b00),                                                              // (terminated),                                       
		.uav_writeresponsevalid (),                                                                   // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                // (terminated),                                       
	);

endmodule
