// SRAM_SC_s10_user_rst_clkgate_1.v

// Generated using ACDS version 19.4 64

`timescale 1 ps / 1 ps
module SRAM_SC_s10_user_rst_clkgate_1 (
		output wire  ninit_done  // ninit_done.ninit_done
	);

	altera_s10_user_rst_clkgate s10_user_rst_clkgate_1 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.ninit_done
	);

endmodule
